
//level_enummethods.go is auto generated by utility enummethods. DO NOT EDIT
//This file have some type methods implementing the Enumerator and json.Marshaler, json.Unmarshaler interfaces.
package cons

import (
	
	"strings"
	"github.com/ivi81/enummethods/enumerator"
)


//IsValid проверка корректности значения
//Реализует интерфейс Validator
func (m Level) IsValid() bool {

	switch m {
	case
		info,
		debug,
		warn,
		err:
		return true
	}
	return false
}


//MarshalJSON - реализует метод интерфейса json.Marshaler
func (m Level) MarshalJSON() ([]byte, error) {
	return enumerator.MarshalJSON(m)
}

//UnmarshalJSON - реализует метод интерфейса json.UnMarshaler
func (m *Level) UnmarshalJSON(data []byte) error {
	return enumerator.UnmarshalJSON(m, data)
}


//MarshalYAML - реализует метод интерфейса yaml.Marshaler
func (m Level) MarshalYAML() (interface{}, error) {
	return enumerator.MarshalYAML(m)
}

//UnmarshalYAML - реализует метод интерфейса yaml.UnMarshaler
func (m *Level) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumerator.UnmarshalYAML(m, unmarshal)
}


//SetValue конвертация строки в значение типа
//Реализует интерфейс Unstringer
func (m *Level) SetValue(s string) bool {
	i := strings.Index(_Level_name, s)
	if i != -1 {

		for index, v := range _Level_index {
			if i-int(v) == 0 {
				*m = Level(index)
				return true
			}
		}
	}
	return false
}

