// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package cons

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stdin-0]
	_ = x[file-1]
	_ = x[storage-2]
}

const _Mode_name = "stdinfilestorage"

var _Mode_index = [...]uint8{0, 5, 9, 16}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
